# Generated by Django 3.2.8 on 2022-01-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_customerentry_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ent',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Product', 'Product'), ('Service', 'Service'), ('Other', 'Other')], max_length=255),
        ),
    ]
