# Generated by Django 3.2.8 on 2022-01-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20220114_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profession',
            field=models.CharField(max_length=200, verbose_name='Profession'),
        ),
    ]
