# Generated by Django 3.2.8 on 2022-01-25 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_myuser_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='profession',
        ),
    ]
